version: "3.8"
services:

  redis:
    image: redis

  server:
    image: gawsoft/cache-grpc-server
    ports:
      - 3000:3000
    environment:
      REDIS_URL: redis://redis:6379
      HOST: 0.0.0.0:3000