version: "3.8"
services:

  redis:
    image: redis
    ports:
      - 6379:6379

  server:
    image: gawsoft/cache-grpc-server
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: redis://redis:6379
      HOST: 0.0.0.0:3000